#!/usr/bin/env node
// ============================================================
// 📖 Vibe Contract — Program README Generator
// Reads the Anchor IDL and program ID, then generates a
// comprehensive markdown file that participants can paste
// into AI chat to build frontends.
// ============================================================

const fs = require("fs");
const path = require("path");

// -- Paths ---------------------------------------------------
const PROJECT_ROOT = path.resolve(__dirname, "..");
const IDL_PATH = path.join(PROJECT_ROOT, "target", "idl", "active_program.json");
const PROGRAM_ID_PATH = path.join(PROJECT_ROOT, "output", "program-id.txt");
const OUTPUT_DIR = path.join(PROJECT_ROOT, "output");
const OUTPUT_PATH = path.join(OUTPUT_DIR, "program-readme.md");

// -- Helpers -------------------------------------------------

function toCamelCase(str) {
  return str.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

// Map IDL type to a plain English description
function describeType(idlType) {
  if (typeof idlType === "string") {
    const map = {
      bool: "boolean (true/false)",
      u8: "unsigned 8-bit integer (0–255)",
      i8: "signed 8-bit integer (-128–127)",
      u16: "unsigned 16-bit integer",
      i16: "signed 16-bit integer",
      u32: "unsigned 32-bit integer",
      i32: "signed 32-bit integer",
      u64: "unsigned 64-bit integer (use BN in JS)",
      i64: "signed 64-bit integer (use BN in JS)",
      u128: "unsigned 128-bit integer (use BN in JS)",
      i128: "signed 128-bit integer (use BN in JS)",
      f32: "32-bit float",
      f64: "64-bit float",
      string: "UTF-8 string",
      publicKey: "Solana public key (base58)",
      pubkey: "Solana public key (base58)",
      bytes: "byte array",
    };
    return map[idlType] || idlType;
  }
  if (idlType.vec) return `array of ${describeType(idlType.vec)}`;
  if (idlType.option) return `optional ${describeType(idlType.option)}`;
  if (idlType.array) return `fixed array of ${describeType(idlType.array[0])}`;
  if (idlType.defined) return `custom type: ${idlType.defined.name || idlType.defined}`;
  return JSON.stringify(idlType);
}

// Map IDL type to TypeScript type for code examples
function idlTypeToTs(idlType) {
  if (typeof idlType === "string") {
    const map = {
      bool: "boolean",
      u8: "number",
      i8: "number",
      u16: "number",
      i16: "number",
      u32: "number",
      i32: "number",
      u64: "BN",
      i64: "BN",
      u128: "BN",
      i128: "BN",
      f32: "number",
      f64: "number",
      string: "string",
      publicKey: "PublicKey",
      pubkey: "PublicKey",
      bytes: "Buffer",
    };
    return map[idlType] || idlType;
  }
  if (idlType.vec) return `${idlTypeToTs(idlType.vec)}[]`;
  if (idlType.option) return `${idlTypeToTs(idlType.option)} | null`;
  if (idlType.array) return `${idlTypeToTs(idlType.array[0])}[]`;
  if (idlType.defined) return idlType.defined.name || idlType.defined;
  return "any";
}

function placeholder(idlType) {
  const tsType = idlTypeToTs(idlType);
  if (tsType === "BN") return `new BN(0)`;
  if (tsType === "boolean") return `false`;
  if (tsType === "number") return `0`;
  if (tsType === "string") return `""`;
  if (tsType === "PublicKey") return `new PublicKey("...")`;
  return `null /* ${tsType} */`;
}

// -- Main ----------------------------------------------------
function main() {
  console.log("");
  console.log("📖 Vibe Contract — Generate Program README");
  console.log("==========================================");
  console.log("");

  // Read IDL
  if (!fs.existsSync(IDL_PATH)) {
    console.log("❌ IDL not found at", IDL_PATH);
    console.log("   💡 Run ./scripts/build.sh first");
    process.exit(1);
  }

  const idl = JSON.parse(fs.readFileSync(IDL_PATH, "utf-8"));
  const programName = idl.metadata?.name || "active_program";
  const instructions = idl.instructions || [];
  const accounts = idl.accounts || [];
  const types = idl.types || [];

  // Read program ID (may not exist yet if not deployed)
  let programId = idl.address || "NOT_YET_DEPLOYED";
  if (fs.existsSync(PROGRAM_ID_PATH)) {
    programId = fs.readFileSync(PROGRAM_ID_PATH, "utf-8").trim();
  }

  // Detect template name from a marker file or default
  let templateName = "unknown";
  const templateMarker = path.join(PROJECT_ROOT, "output", "template-name.txt");
  if (fs.existsSync(templateMarker)) {
    templateName = fs.readFileSync(templateMarker, "utf-8").trim();
  }

  console.log(`📋 Program: ${programName}`);
  console.log(`🔑 Program ID: ${programId}`);
  console.log(`📦 Instructions: ${instructions.length}`);
  console.log(`📁 Template: ${templateName}`);
  console.log("");

  // Build markdown
  let md = "";

  // -- Title
  md += `# ${programName}\n\n`;
  md += `> Generated by **Vibe Contract** — a Solana smart contract factory.\n\n`;

  // -- Overview table
  md += `## Overview\n\n`;
  md += `| Field | Value |\n`;
  md += `|-------|-------|\n`;
  md += `| **Program ID** | \`${programId}\` |\n`;
  md += `| **Network** | Solana devnet |\n`;
  md += `| **Template** | ${templateName} |\n`;
  md += `| **Framework** | Anchor ${idl.metadata?.spec || "0.1.0"} |\n`;
  md += `| **Instructions** | ${instructions.length} |\n`;

  const explorerUrl = `https://explorer.solana.com/address/${programId}?cluster=devnet`;
  md += `| **Explorer** | [View on Solana Explorer](${explorerUrl}) |\n`;
  md += `\n`;

  // -- Instructions
  md += `## Instructions\n\n`;

  if (instructions.length === 0) {
    md += `_No instructions found in the IDL._\n\n`;
  }

  for (const ix of instructions) {
    const ixAccounts = ix.accounts || [];
    const ixArgs = ix.args || [];

    md += `### \`${ix.name}\`\n\n`;

    // Args
    if (ixArgs.length > 0) {
      md += `**Parameters:**\n\n`;
      md += `| Name | Type | Description |\n`;
      md += `|------|------|-------------|\n`;
      for (const a of ixArgs) {
        md += `| \`${a.name}\` | ${describeType(a.type)} | — |\n`;
      }
      md += `\n`;
    } else {
      md += `**Parameters:** _none_\n\n`;
    }

    // Accounts
    if (ixAccounts.length > 0) {
      md += `**Accounts:**\n\n`;
      md += `| Name | Writable | Signer | Description |\n`;
      md += `|------|----------|--------|-------------|\n`;
      for (const acc of ixAccounts) {
        const writable = acc.writable ? "Yes" : "No";
        const signer = acc.signer ? "Yes" : "No";
        md += `| \`${acc.name}\` | ${writable} | ${signer} | — |\n`;
      }
      md += `\n`;
    } else {
      md += `**Accounts:** _none_\n\n`;
    }

    // TypeScript example
    md += `**TypeScript Example:**\n\n`;
    md += "```typescript\n";

    const fnName = toCamelCase(ix.name);
    md += `const txSig = await program.methods\n`;
    md += `  .${fnName}(`;

    if (ixArgs.length > 0) {
      md += `\n`;
      for (let i = 0; i < ixArgs.length; i++) {
        const a = ixArgs[i];
        const comma = i < ixArgs.length - 1 ? "," : "";
        md += `    ${placeholder(a.type)}${comma} // ${a.name}\n`;
      }
      md += `  `;
    }
    md += `)\n`;

    if (ixAccounts.length > 0) {
      md += `  .accounts({\n`;
      for (const acc of ixAccounts) {
        md += `    ${toCamelCase(acc.name)}: ${toCamelCase(acc.name)}PublicKey,\n`;
      }
      md += `  })\n`;
    }
    md += `  .rpc();\n`;
    md += "```\n\n";
  }

  // -- Account types (if any defined account structs)
  if (accounts.length > 0) {
    md += `## Account Types\n\n`;
    for (const acc of accounts) {
      md += `### \`${acc.name}\`\n\n`;
      // Find the corresponding type definition
      const typeDef = types.find((t) => (t.name === acc.name));
      if (typeDef && typeDef.type && typeDef.type.fields) {
        md += `| Field | Type |\n`;
        md += `|-------|------|\n`;
        for (const f of typeDef.type.fields) {
          md += `| \`${f.name}\` | ${describeType(f.type)} |\n`;
        }
        md += `\n`;
      }
    }
  }

  // -- Custom types (non-account types like enums)
  const nonAccountTypes = types.filter(
    (t) => !accounts.some((a) => a.name === t.name)
  );
  if (nonAccountTypes.length > 0) {
    md += `## Custom Types\n\n`;
    for (const t of nonAccountTypes) {
      md += `### \`${t.name}\`\n\n`;
      if (t.type && t.type.kind === "enum" && t.type.variants) {
        md += `Enum variants: ${t.type.variants.map((v) => `\`${v.name}\``).join(", ")}\n\n`;
      } else if (t.type && t.type.fields) {
        md += `| Field | Type |\n`;
        md += `|-------|------|\n`;
        for (const f of t.type.fields) {
          md += `| \`${f.name}\` | ${describeType(f.type)} |\n`;
        }
        md += `\n`;
      }
    }
  }

  // -- Full IDL
  md += `## Full IDL (JSON)\n\n`;
  md += `<details>\n`;
  md += `<summary>Click to expand</summary>\n\n`;
  md += "```json\n";
  md += JSON.stringify(idl, null, 2);
  md += "\n```\n\n";
  md += `</details>\n\n`;

  // -- Quick Start
  md += `## Quick Start\n\n`;
  md += `To interact with this program from a frontend or script:\n\n`;
  md += "```bash\n";
  md += `npm install @coral-xyz/anchor @solana/web3.js\n`;
  md += "```\n\n";
  md += "```typescript\n";
  md += `import { AnchorProvider, Program, setProvider } from "@coral-xyz/anchor";\n`;
  md += `import { Connection, PublicKey, clusterApiUrl } from "@solana/web3.js";\n`;
  md += `import idl from "./idl.json";\n\n`;
  md += `const connection = new Connection(clusterApiUrl("devnet"), "confirmed");\n`;
  md += `const provider = new AnchorProvider(connection, wallet, { commitment: "confirmed" });\n`;
  md += `setProvider(provider);\n\n`;
  md += `const program = new Program(idl as any, provider);\n`;
  md += "```\n\n";

  // -- Footer
  md += `---\n\n`;
  md += `_Generated by [Vibe Contract](https://github.com/anthropics/vibecontract) — paste this file into AI chat to build a frontend._\n`;

  // Write output
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, md, "utf-8");

  console.log(`✅ Generated: ${OUTPUT_PATH}`);
  console.log("");
}

main();
